# Defines a small topology of 3 routers, 5 networks and 2 endpoints
# docker compose -f compose.yaml --profile routers up -d
# docker compose -f compose.yaml --profile endpoints --profile routers up -d
# docker compose -f compose.yaml --profile routers --profile endpoints down -t 1
services:

  # 3 routers connecting networks
  router1:
    profiles: ["routers"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 server.py 172.22.0. 172.23.0. 192.168.0. 2.0
    stdin_open: true
    tty: true
    environment:
      HOSTNAME: router1
    networks:
      - network1
      - rnetwork1

#- tcpdump -i eth1 -c 10 -w /compnets/router2.pcap
    #  - nc -l -u 

  router2:
    profiles: ["routers"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 server.py 172.22.0. 172.21.0. 0.2
    stdin_open: true
    tty: true
    environment:
      HOSTNAME: router2
    networks:
      - rnetwork1
      - network2

  # 2 endpoints creating traffic
  client1:
    profiles: ["endpoints"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 client.py 192.168.0. 146 169
    stdin_open: true
    tty: true
    depends_on:
      - router1
    environment:
      HOSTNAME: client1
    networks:
      - network1

  client2:
    profiles: ["endpoints"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 client.py 172.21.0. 169 146
    stdin_open: true
    tty: true
    depends_on:
      - router1
    environment:
      HOSTNAME: client2
    networks:
      - network2


# 2 Stub networks and 3 transient networks
networks:
  network1:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  network2:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
  rnetwork1:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
  rnetwork2:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
